FROM python:3.11-slim
ARG VERSION=0.1.1
WORKDIR /opt/StaticJinjaPlus
ADD --checksum=sha256:30d9424df1eddb73912b0e2ad5375fa2c876c8e30906bec91952dfb75dcf220b https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/0.1.1.tar.gz /tmp/app-0.1.1.tar.gz
ADD --checksum=sha256:3555bcfd670e134e8360ad934cb5bad1bbe2a7dad24ba7cafa0a3bb8b23c6444 https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/0.1.0.tar.gz /tmp/app-0.1.0.tar.gz
RUN if [ "$VERSION" = "0.1.1" ]; then \
        tar xzf /tmp/app-0.1.1.tar.gz --strip-components=1 -C /opt/StaticJinjaPlus && rm /tmp/app-0.1.1.tar.gz; \
    elif [ "$VERSION" = "0.1.0" ]; then \
        tar xzf /tmp/app-0.1.0.tar.gz --strip-components=1 -C /opt/StaticJinjaPlus && rm /tmp/app-0.1.0.tar.gz; \
    fi
RUN python3 -m venv venv \
    && venv/bin/pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["./venv/bin/python", "main.py"]
CMD ["--srcpath=data/templates/", "--outpath=data/build/"]



